### ISSUE TITLE
Update pytests to run under Python 3.11

### ISSUE THREAD

**Issue by asgibson** [nasa/OnAIR#14]
Tests run under Python 3.9 without error. Under 3.11 there are 3 failing tests:
test_Simulator__init__creates_Vehicle_and_AdapterDataSource_from_parsed_data_and_Agent_with_vehicle_when_SBN_Flag_resolves_to_True
test_ExecutionEngine_parse_data_argument_subsystems_breakdown_optional_default_is_False
test_ExecutionEngine_parse_data_sets_the_processedSimData_to_the_TimeSynchronizer_which_was_given_the_sim_data_received_from_parsed_data

**Comment by kokroo** [comment]
Do you have an error log? I would love to help with this.

**Comment by asgibson** [comment]
@kokroo, you are welcome to help!

I created branch [14-update-pytests-to-run-under-python-311](https://github.com/nasa/OnAIR/tree/14-update-pytests-to-run-under-python-311) for code changes. 
That has the CI running with Python 3.11.2, showing the 3 failures here: https://github.com/nasa/OnAIR/actions/runs/5868774652/job/15912332928

Thank you for your interest in collaborating!
If you want to submit a pull request please see the contributions guidelines:
https://github.com/nasa/OnAIR/tree/main#contributions

**Comment by kokroo** [comment]
@asgibson Thank you for the warm welcome!

I have just submitted the Individual Contributor License Agreement over e-mail. I will start fixing this issue and I hope my e-mail will get processed by the time I create a PR.

Cheers!

**Comment by kokroo** [comment]
@asgibson 
<img width="816" alt="Screenshot 2023-08-15 at 21 35 15" src="https://github.com/nasa/OnAIR/assets/6683709/40ecc0ec-3ab7-4144-93cd-c3ec766a1010">

This test fails sometimes and sometimes it doesn't. The reason is, when it's a single mock object, it is passed straight instead of being as a list.

<img width="392" alt="Screenshot 2023-08-15 at 21 35 47" src="https://github.com/nasa/OnAIR/assets/6683709/4d7b28a1-b689-45cf-b81b-a65eac198b91">

When there are multiple headers, it is passed as a list and the assertion works.
Should I check for the presence of a single mock object and cast it as a list right before the assertion?

<img width="950" alt="Screenshot 2023-08-15 at 21 36 39" src="https://github.com/nasa/OnAIR/assets/6683709/6332b471-b33d-4685-85a9-d83c0f8a0570">

**Comment by asgibson** [comment]
@kokroo, thanks for digging into this. If the test in the above is a test in test_sim.py (it is unclear exactly which test this is from your outputs) then the problem is that it should not even be reaching that `assert(len(headers)>0)` because that is in the DataDrivenLearning.__init__ which means that the unit test paradigm is broken. No code outside of the method called during the unit test should be running.

Specifically if this is the test 'test_Simulator__init__creates_Vehicle_and_AdapterDataSource_from_parsed_data_and_Agent_with_vehicle_when_SBN_Flag_resolves_to_True' then I see two issues.

1. There are two tests that have the same name, probably just an oversight, the second one defined is the one that runs.
2. The code under test (cut) is Simulation.__init__, but it appears that the Agent from the line `self.agent = Agent(vehicle)` is not being mocked and is running its code incorrectly. This is breaking the unit test paradigm where the cut should be isolated from all other code. Something changed between 3.9 and 3.11 that is causing it to no longer mock the `Agent(vehicle)` call. In 3.9 the instantiation of the Agent object mocks correctly (all assertions pass), but in 3.11 it is (incorrectly for a unit test) calling the actual production code for the Agent.

**Comment by kokroo** [comment]
@asgibson Thank you for your guidance. I have suspected since the beginning that this has to do with how paths are handled in 3.11
I ran the test suite on 3.10.x and they all passed, so the changes happened in 3.11

I will need to dig deeper into the internals of Python itself as well as the mock library to find out why it's calling the actual production code.

**Comment by asgibson** [comment]
Here is some further diagnosis information:

For the test named:
**test_Simulator__init__creates_Vehicle_and_AdapterDataSource_from_parsed_data_and_Agent_with_vehicle_when_SBN_Flag_resolves_to_True**

### Python 3.9 (correct output): 
FakeDataAdapterSource from test ==  <class 'test_sim.<test_name>.\<locals>.FakeDataAdapterSource'>
FakeDataAdapterSource in CUT    ==  <class 'test_sim.<test_name>.\<locals>.FakeDataAdapterSource'>
fake_agent in CUT  ==  \<MagicMock name='Agent' id='###'>

### Python 3.11 (incorrect output):
FakeDataAdapterSource from test ==  <class 'test_sim.\<test_name>.\<locals>.FakeDataAdapterSource'>
FakeDataAdapterSource in CUT    ==  \<MagicMock name='mock.AdapterDataSource' id='###'>
fake_agent in CUT  ==  <class 'onair.src.reasoning.agent.Agent'>

**Comment by asgibson** [comment]
Recent changes in OnAIR have resulted in changes to test operations.
This test no longer exists:
test_Simulator__init__creates_Vehicle_and_AdapterDataSource_from_parsed_data_and_Agent_with_vehicle_when_SBN_Flag_resolves_to_True 
The remaining two tests were updated due to changes in execution_engine.py and no longer suffer from the problem.

One additional problem from 3.9 to 3.11 was noticed. The use of `str(MagicMock())` under 3.9 had no issues with creating random strings because the ID was always unique, but under 3.11 IDs were occasionally being reused and resulting in random failures (only a few per hundred, but any random fails are not acceptable).

These were updated to use unique numbers as strings for the tests that were having issues.
