### ISSUE TITLE
remove the flags we dont use

### ISSUE THREAD

**Issue by Evana13G** [nasa/OnAIR#60]
- Viz

**Comment by asgibson** [comment]
There are 3 flags: IO, Dev, and Viz. The setting of the values for these is via .ini file.

It appears that Dev is similar in use to Viz. They both are set, passed, but never checked.  
Only IO appears to be used. It is set up to be the controller of output. Running with IO as `True` produces output. As `False` there is no ouput and OnAIR runs completely silent. There is also something checking if it is "strict", but that cannot be set in a config file due to: 
```
ValueError: Not a boolean: "strict"
```
It is never set to that value anywhere in the code.

@Evana13G should both Dev and Viz be removed? Should we allow for multiple IO settings or, remove the "strict" check and keep it as an on/off setting?

**Comment by Evana13G** [comment]
When these flags were originally created, it was for the following purpose - 1) Dev was set to bypass apriori training, 2) viz was for dumping JSON data into a results file and launching a d3-based (web front end) interface, and 3) IO was for terminal IO. That being said, I think we should keep just IO. For the IO question, we had created the "strict" setting because we were having some performance issue with writing to the terminal. I suggest we remove strict, and eventually, integrate logging for folks to keep a trace if they want. Thoughts?

**Comment by asgibson** [comment]
Agreed. Dev and Viz don't make sense any more, given your explanation for their existence. I will remove their usage as well as the check for "strict." We can even revisit having different levels of verbosity for the terminal output and incorporate loggin, but for this particular issue, we are set.
